// Generated by CoffeeScript 1.3.3

/*
  mdhtmlform - Simple Example
  This file just handles form submissions for this example.
*/

(function() {

  $(function() {
    return $("button.submit").on("click", function(e) {
      password = $("input.form-control").val();
      if (CryptoJS.SHA256(password).toString() == '5d6e0eecd32302adf4ad5e712f8f4e1db7cd9f9d37b0a1c1503aca6ee8ea7e44') {
        var myDataRef = new Firebase('https://arkadyark.firebaseio.com/blog-posts')
        var html;
        html = $("textarea.mdhtmlform-html").val();
        myDataRef.push({post: html});
        console.log("hey!");
      } 
    });
  });

}).call(this);
