// Generated by CoffeeScript 1.3.3

/*
  mdhtmlform - Simple Example
  This file just handles form submissions for this example.
*/


(function() {

  $(function() {
    return $("button.submit").on("click", function(e) {
      var myDataRef = new Firebase('https://arkadyark.firebaseio.com/blog-posts')
      var html;
      e.preventDefault();
      html = $("textarea.mdhtmlform-html").val();
      myDataRef.set({post: html});
      console.log("hey!");
    });
  });

}).call(this);
